#! /usr/bin/env python
# encoding: utf-8


def options(opt):
    import waflib.extras.wurf_dependency_bundle as bundle
    import waflib.extras.wurf_dependency_resolve as resolve

    bundle.add_dependency(opt, resolve.ResolveGitMajorVersion(
        name='waf-tools',
        git_repository='github.com/steinwurf/waf-tools.git',
        major_version=2))

    bundle.add_dependency(opt, resolve.ResolveGitMajorVersion(
        name='waf-build-statistics',
        git_repository='github.com/steinwurf/waf-build-statistics.git',
        major_version=1))

    opt.load("wurf_configure_output")
    opt.load('wurf_dependency_bundle')
    opt.load('wurf_tools')


def configure(conf):

    conf.load('wurf_dependency_bundle')
    conf.load('wurf_tools')

    conf.load_external_tool('install_path', 'wurf_install_path')
    conf.load_external_tool('mkspec', 'wurf_cxx_mkspec_tool')
    conf.load_external_tool('project_gen', 'wurf_project_generator')
    conf.load_external_tool('runners', 'wurf_runner')

    conf.recurse([conf.dependency_path('waf-build-statistics')])


def build(bld):
    bld.recurse('src/test_project')
